### ISSUE TITLE
bitcoin-cli getblockcount failed

### ISSUE THREAD

**Issue by Dylanma1994** [OrdDeFi/OrdDeFi-Virtual-Machine#1]
Run `bitcoin-cli getblockcount`, and i got correct response.
When i run `OrdDefi-Virtual-Machine.exe`, i got `bitcoin-cli getblockcount failed`

<img width="526" alt="image" src="https://github.com/OrdDeFi/OrdDeFi-Virtual-Machine/assets/134244473/08e7b677-0de6-42b5-89ae-7f037ca8e9e2">

**Comment by weiduiqwq** [comment]
Not compatible with windows

**Comment by Dylanma1994** [comment]
Windows is ok. just add strings.TrimSpace
<img width="787" alt="image" src="https://github.com/OrdDeFi/OrdDeFi-Virtual-Machine/assets/134244473/78be7658-38fa-4503-83cf-0a88f4464655">

**Comment by renmengkai** [comment]
windows同样碰到过这个问题，感谢大佬已经解决了。但是大佬有没有碰到下面截图这个问题？直接运行 bitcoin-cli getblock xxx
 命令没问题 但是程序就是会报错
![image](https://github.com/OrdDeFi/OrdDeFi-Virtual-Machine/assets/31378513/273eac87-158e-4281-b1fb-6ae28e8ae51e)

**Comment by weiduiqwq** [comment]
Already tested, just change to strings.TrimSpace() to run on windows
you can follow the modifications of my pull request
https://github.com/OrdDeFi/OrdDeFi-Virtual-Machine/pull/2

**Comment by OrdDeFi** [comment]
Fixed at pr #2

**Comment by jerrywjh** [comment]
This problem occurs on Mac OS too.   If the blockchain data (-datadir ) is not located in the default directory, the bitcoin-cli will fail.  Should be a bug.

**Comment by jerrywjh** [comment]
Please reopen this ticket
