### ISSUE TITLE
GetRawTransaction Error: exit status 5

### ISSUE THREAD

**Issue by 0xLxcas** [OrdDeFi/OrdDeFi-Virtual-Machine#3]
![image](https://github.com/OrdDeFi/OrdDeFi-Virtual-Machine/assets/133096759/ffdd7fcc-4b6b-4644-8607-00b6ca422854)

Can you help me ? I can't index

**Comment by cradle0fFilth** [comment]
This because you have synchronize blocks without proper configuration.Firstly,edit your bitcoin.conf file as "txindex=1 server=1" and use "bitcoind -reindex"command to reindex datas.
